# Generated by Django 4.0.4 on 2022-07-18 18:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('listing', models.CharField(max_length=100)),
                ('listing_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(max_length=255)),
                ('contact_date', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.UUIDField(blank=True, null=True)),
            ],
        ),
    ]
