# Generated by Django 4.0.4 on 2022-07-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_listing_pub_date'),
        ('contacts', '0003_remove_businessinquiry_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='listing_details',
            field=models.ManyToManyField(blank=True, to='properties.listing'),
        ),
    ]
