# Generated by Django 4.0.4 on 2022-07-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_avatar',
            field=models.CharField(default='https://res.cloudinary.com/iamalmiir/image/upload/v1657350671/catAvatar_iakq5p.jpg', max_length=255),
        ),
    ]
