# Generated by Django 4.0.4 on 2022-06-03 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='ID',
            new_name='id',
        ),
    ]
