# Generated by Django 4.0.4 on 2022-06-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_id_property_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
