# Generated by Django 4.0.4 on 2022-06-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_photo_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='cooling',
            field=models.CharField(choices=[('Central', 'Central'), ('Electric', 'Electric'), ('None', 'None')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='heating',
            field=models.CharField(choices=[('Central', 'Central'), ('Electric', 'Electric'), ('Forced Air', 'Forced Air'), ('Natural Gas', 'Natural Gas'), ('Fireplace', 'Fireplace'), ('None', 'None')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='property',
            name='pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.IntegerField(default=2022),
        ),
    ]
