# Generated by Django 4.0.4 on 2022-06-28 11:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_cooling_property_heating_property_pool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cooling',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Central', 'Central'), ('Electric', 'Electric'), ('None', 'None')], default='None', max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='heating',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Central', 'Central'), ('Electric', 'Electric'), ('Forced Air', 'Forced Air'), ('Natural Gas', 'Natural Gas'), ('Fireplace', 'Fireplace'), ('None', 'None')], default='None', max_length=30),
        ),
    ]
