# Generated by Django 4.0.4 on 2022-06-28 11:20

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_cooling_alter_property_heating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='cooling',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Central', 'Central'), ('Electric', 'Electric'), ('No data', 'No data')], default='None', max_length=70),
        ),
        migrations.AlterField(
            model_name='property',
            name='heating',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Central', 'Central'), ('Electric', 'Electric'), ('Forced Air', 'Forced Air'), ('Natural Gas', 'Natural Gas'), ('Fireplace', 'Fireplace'), ('No data', 'No data')], default='None', max_length=70),
        ),
    ]
