# Generated by Django 4.0.4 on 2022-07-08 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_listing_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='publishedAt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 8, 16, 39, 57, 971871)),
        ),
    ]
