# Generated by Django 4.0.4 on 2022-07-11 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_listing_publishedat_alter_listing_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 11, 16, 7, 33, 186745)),
        ),
    ]
