# Generated by Django 4.0.4 on 2022-06-28 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_alter_realtor_photo'),
        ('properties', '0013_alter_property_realtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='type_of_property',
            field=models.CharField(choices=[('Single Family', 'Single Family'), ('Condo', 'Condo'), ('Townhouse', 'Townhouse'), ('Multi-Family', 'Multi-Family'), ('Duplex', 'Duplex')], default='Single Family', max_length=50),
        ),
        migrations.AlterField(
            model_name='property',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='realtor', to='realtors.realtor'),
        ),
        migrations.AlterUniqueTogether(
            name='property',
            unique_together={('realtor', 'pub_date')},
        ),
    ]
