# Generated by Django 4.0.4 on 2022-05-29 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_alter_realtor_hire_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='id',
            new_name='ID',
        ),
    ]
